### ISSUE TITLE
weird elementalcraft thing

### ISSUE THREAD

**Issue by freopt** [Shadows-of-Fire/FastSuite#16] opened 2022-02-06 01:05 UTC
having elementalcraft and dpanvil installed with fastsuite causes it to spam log with errors on world load

with ec and dpa: https://paste.ee/p/8c4lV
without: 
[19:57:47] [Render thread/INFO]: Successfully processed 14931 recipes into the AuxRecipeManager.
[19:57:47] [Server thread/ERROR]: Unknown structure start: elementalcraft:source_altar
regular log stuff

seeing as theres an open issue involving elementalcraft there seems to be some sort of incompatability

**Comment by Shadows-of-Fire** [comment] 2022-02-06 03:45
The unknown recipe category warning is not an error nor related to FS - it just occurs whenever any recipe exists that is not of a default vanilla type.

Closing as duplicate of #15

**Closed as completed by Shadows-of-Fire** 2022-02-06 03:45 UTC
